require("lazy").setup({
    spec = {
        { import = "after.plugins" },
    },
    change_detection = {
        enable = false,
        notify = false,
    },
    checker = { enabled = false },
    concurrency = 2,
    performance = {
        cache = { enabled = true },
        reset_packpath = true,
        rtp = {
            disabled_plugins = {
                "2html_plugin",
                "bugreport",
                "compiler",
                "ftplugin",
                "getscript",
                "getscriptPlugin",
                "gzip",
                "logipat",
                "matchit",
                "matchparen",
                "optwin",
                "rplugin",
                "rrhelper",
                "spellfile_plugin",
                "synmenu",
                "syntax",
                "tar",
                "tarPlugin",
                "tohtml",
                "tutor",
                "vimball",
                "vimballPlugin",
                "zip",
                "zipPlugin",
                -- "netrwPlugin",
                -- "netrwSettings",
                -- "netrwFileHandlers",
            },
        },
    },
})

